name: Code Quality and Test

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Set this to your project's node version

      - name: Install Dependencies
        run: npm install pnpm && pnpm install


      - name: Run Prettier Check
        run: npx prettier --check '**/**/*.{js,jsx,ts,tsx,css}'
      
      - name: Run ESLint Check
        run: npx eslint --fix

